### ISSUE TITLE
Errror...

### ISSUE THREAD

**Issue by ImTheReal99** [Flowx3/Nostale-Register-Website#1]
Fatal error: Uncaught Exception: could not find driver in C:\xampp\htdocs\vendor\catfan\medoo\src\Medoo.php:240 Stack trace: #0 C:\xampp\htdocs\config\Database.php(55): Medoo\Medoo->__construct(Array) #1 C:\xampp\htdocs\index.php(193): Database('1', NULL) #2 {main} thrown in C:\xampp\htdocs\vendor\catfan\medoo\src\Medoo.php on line 240

Würde mich freuen, wenn du mir helfen könntest.. ^^

**Comment by Flowx3** [comment]
You need to instal mssql Driver for xampp then the Problem is fixed.
